### ISSUE TITLE
Feature Request: Close improvements and Handling Normal Close

### ISSUE THREAD

**Issue by Eisa01** [jellyfin/jellyfin-desktop#173] opened 2021-03-14 20:29 UTC
**Is your feature request related to a problem? Please describe.**
Currently exiting in any normal way, other than <kbd>q</kbd> or by pressing [x] on top bar when borders enabled causes crash. Also, there is a very noticeable wait-time before the player closes.
It is currently not possible to handle close by any other way even caps <kbd>Q</kbd> causes crash. closing on [x] on top bar with no-borders option crashes, scripts sending exit crashes, etc. 

**Describe the solution you'd like**
It would be very pleasing if normal close would work, as there are many OSCs improvements that can be implemented once it is fixed.

**Describe alternatives you've considered**
Additionally to fix the exit delay and the main issue, perhaps handling sending the time back to Jellyfin server is the reason why wait time is needed? I have scripted a solution to get real-time of video at all times without delay, perhaps it could help https://github.com/Eisa01/mpv-scripts#smarthistory-script-171

**Additional context**
As the code is large, if you could refer me to where I could start, perhaps I could have a look and try to work my way into improving the functionality.

**Comment by iwalton3** [comment] 2021-03-14 20:47
This is a duplicate of https://github.com/jellyfin/jellyfin-desktop/issues/110.

"Handling Normal Close" means handling a termination of the MPV process. While this is possible with the underlying libraries, currently the software is written with the assumption that MPV is never terminated and a large number of changes would be required to deal with MPV not being present and restarting it on demand.

If you would like to look at it, the https://github.com/jellyfin/jellyfin-desktop/blob/master/jellyfin_mpv_shim/player.py is what instantiates MPV and is where *most* of the direct access occurs. (I believe some also occurs in the SyncPlay module.) I am currently using two interchangeable MPV libraries which may handle termination slightly differently. They are https://github.com/jaseg/python-mpv and https://github.com/iwalton3/python-mpv-jsonipc.

There are two solutions:
 - Third-party extensions can be modified to stop playback (which closes the window and leaves MPV intact).
 - This software can be refactored to support handling process termination and restarting.

The latter could be done, but I simply do not have the time to prioritize that. Pull requests are welcome but I will prioritize more urgent things like making SyncPlay work and updating the web client for now.

**Closed by iwalton3** 2021-03-14 20:47 UTC
