### ISSUE TITLE
Playing soft links to videos in Linux

### ISSUE THREAD

**Issue by busywhistling** [jellyfin/jellyfin-desktop#172] opened 2021-03-14 13:04 UTC
`jellyfin-mpv-desktop` can't play videos when they are a soft link to the appropriate file. The file permissions are the same, and the video is playable in the browser version (even with transcoding). The video is added to the library but can't be played with `mpv`. Is this a bug in the implementation?

**Comment by iwalton3** [comment] 2021-03-14 14:05
This is a problem with direct play on the Jellyfin server and also affects Kodi and Infuse. The server returns a 500 error when trying to read the file.

You can use bindfs for now to bypass the issue. https://bindfs.org

**Comment by busywhistling** [comment] 2021-03-14 14:31
Do you mean I should raise this issue at the Jellyfin server repo? Also, regarding `bindfs`, is there a way to use it without altering my local file structure too much (because I'm tracking some files with git). For example, my setup is:
`file1` scraped by jellyfin, but actually `file1` points to `file2` in a different directory. What should I do with bindfs in this case? Many thanks for your help.

**Comment by iwalton3** [comment] 2021-03-14 16:26
The Jellyfin devs are aware of the issue with symlinks but I don't have the issue number offhand.

Bindfs what you would do is leave all your files alone and mount the bindfs on a separate folder. Then point Jellyfin at that and it'll resolve the symlinks.

**Comment by mcarlton00** [comment] 2021-03-14 17:12
iirc it's actually a dotnet issue from what I've gathered in chat, but I don't remember any details specifically.

**Comment by iwalton3** [comment] 2021-03-14 17:32
This issue is applicable: https://github.com/jellyfin/jellyfin/issues/5521
The problem is .NET does not support or deal with symbolic links. See here: https://github.com/dotnet/runtime/issues/24271

If you would like to work around this issue, you can use bindfs as follows:
```
bindfs --resolve-symlinks /path/to/real/library /path/to/mount
```
Where `/path/to/real/library` is the path to your current library and `/path/to/mount` is the directory that you point Jellyfin at. Please note that you MUST make sure this runs before Jellyfin starts or it may have unwanted effects on your media library.

I am closing this as it does not pertain to the desktop client.

**Closed by iwalton3** 2021-03-14 17:32 UTC
Labels: Has Workaround, invalid

**Comment by oddstr13** [comment] 2021-03-14 18:13
Also note that hardlinks are a viable alternative to symlinks when it's on the same filesystem.

**Comment by busywhistling** [comment] 2021-03-14 22:53
Thanks for the explanation @iwalton3 . Good suggestion @oddstr13 , however, my use case involved working with `git-annex` which only deals with soft links.
